spring:
  cloud:
    config:
      # 如果修改了默认端口，则客户端项目就不能在 application.yml 或 application.properties 中配置 spring.cloud.config.uri，
      # 必须在 bootstrap.yml或是 bootstrap.properties 中配置，原因是 bootstrap 开头的配置文件会被优先加载和配置
      uri: http://localhost:8888
      name: application-feign
      profile: dev
      label: master

#
#server:
#  port: 8202
#
## 将本服务注册到eureka
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ # eureka服务器地址
#
## feign启用熔断
#feign:
#  hystrix:
#    enabled: true