spring:
  application:
    name: spring-cloud-gateway
  # 链路追踪服务器
  zipkin:
      base-url: http://localhost:9411

server:
  port: 8111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# zuul配置
zuul:
  routes:
    api-a:
      path: /api/ribbon/**
      serviceId: spring-cloud-client-ribbon
    api-b:
      path: /api/feign/**
      serviceId: spring-cloud-client-feign