spring:
  application:
    name: spring-cloud-config
  # cloud配置
  cloud:
    config:
      #配置仓库的分支
      label: master
      server:
        git:
          #配置 Git 仓库地址
          uri: https://github.com/terryliu1994/spring-cloud-demo
          # 配置仓库路径（存放配置文件的目录）
          search-paths: configs
          username: terryliu1994
          password: ltl94018


# Config 的端口不能
server:
  port: 8888

# 将本服务注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # eureka服务器地址