spring:
  application:
    name: spring-cloud-service-provider
  # 链路追踪服务器
  zipkin:
      base-url: http://localhost:9411
server:
  port: 8101

# 将本服务注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # eureka服务器地址