spring:
  application:
    name: spring-cloud-zipkin

server:
  port: 9411

# 将本服务注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # eureka服务器地址

# 监控
management:
  metrics:
    web:
      server:
        auto-time-requests: false